[package]
name = "somedb"
version.workspace = true
description.workspace = true
edition.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
somedb-macros.workspace = true
